### ISSUE TITLE
Extend light beams near the mirror

### ISSUE THREAD

**Issue by waldyrious** [TiagoLeite07/ComputerGeneratedHolography_VirtualLab#1]
They should stop after all of the cylinder is "inside" the mirror, not only when its midpoint reaches the mirror surface.

Image:
![Imgur](http://i.imgur.com/CrFz0ML.png)

**Comment by TiagoLeite07** [comment]
Thanks.

The issue is resolved.

**Comment by waldyrious** [comment]
Hmm, I still see the problem. Have you pushed the commit that fixes this to the public repo here on github?

**Comment by TiagoLeite07** [comment]
The problem is solved on the develop branch
